name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
- push
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test DateCheck
      id: test-datecheck
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test DateCheck
        setup-command: ''
        command: python -m unittest tests/testDateCheck.py
        timeout: 1
        max-score: 2
    - name: Test Email Check
      id: test-email-check
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Email Check
        setup-command: ''
        command: python -m unittest tests/testEmailCheck.py
        timeout: 1
        max-score: 2
    - name: Test Favorite
      id: test-favorite
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Favorite
        setup-command: ''
        command: python -m unittest tests/testFavorite2.py
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-DATECHECK_RESULTS: "${{steps.test-datecheck.outputs.result}}"
        TEST-EMAIL-CHECK_RESULTS: "${{steps.test-email-check.outputs.result}}"
        TEST-FAVORITE_RESULTS: "${{steps.test-favorite.outputs.result}}"
      with:
        runners: test-datecheck,test-email-check,test-favorite
